global:
  domain: cd.mini.skov.run

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
      - hosts:
        - cd.mini.skov.run
        # Based on the ingress controller used secret might be optional
        secretName: wildcard-tls