apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm
  namespace: argocd
spec:
  project: default
  sources: 
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.0
    helm:
      valueFiles:
      - $values/cert-manager-values.yaml
  - repoURL: https://github.com/simcax/minikube-test
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true
