apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator-helm
  namespace: argocd
spec:
  project: default
  sources: 
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-operator
    targetRevision: 0.84.2
    helm:
      valueFiles:
      - $values/application-values/otel-operator-values.yaml
  - repoURL: https://github.com/simcax/minikube-test
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true
